/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryGrid: typeof import('./src/components/CategoryGrid.vue')['default']
    Commitment: typeof import('./src/components/Commitment.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    Layout: typeof import('./src/components/layout.vue')['default']
    ProfliewebCard: typeof import('./src/components/profliewebCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    ShortcutGrid: typeof import('./src/components/ShortcutGrid.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    WebsiteCard: typeof import('./src/components/WebsiteCard.vue')['default']
    WebsiteexpressCard: typeof import('./src/components/WebsiteexpressCard.vue')['default']
  }
}
